# -*- coding: utf-8 -*-
"""DecisionTree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1WF27yd31XZMfD9ArpdZ0n7SEN7OWu1
"""

import pandas as pd

file=pd.read_csv("/content/diabetes.csv")

file

input=file[["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]]
output=file["Outcome"]

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()

model.fit(input,output)

model.predict([[6,148,72,35,0,33.6,0.627,50]])

model.predict([["4","110","59","35","0","32.6","0.1","50"]])

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(file, hue="Outcome")
plt.show()

features = ["Pregnancies","Glucose","BloodPressure",
            "SkinThickness","Insulin","BMI",
            "DiabetesPedigreeFunction","Age"]

for feature in features:
    plt.figure()
    plt.scatter(file[feature], file["Outcome"], c=file["Outcome"])
    plt.xlabel(feature)
    plt.ylabel("Outcome")
    plt.title(feature + " vs Outcome")
    plt.show()

plt.scatter(file["Glucose"], file["Outcome"])
plt.xlabel("Glucose")
plt.ylabel("Outcome")
plt.show()

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(file["Glucose"], file["BMI"], file["Age"],
           c=file["Outcome"])

ax.set_xlabel("Glucose")
ax.set_ylabel("BMI")
ax.set_zlabel("Age")

plt.show()

plt.figure(figsize=(15,10))

for i, feature in enumerate(features):
    plt.subplot(3,3,i+1)
    plt.scatter(file[feature], file["Outcome"])
    plt.title(feature)

plt.tight_layout()
plt.show()