# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyYZ3NaXKyXf9DzJN38GhU9H6DLADXh2
"""

import pandas as pd

from sklearn.neighbors import KNeighborsClassifier

file = pd.read_csv("/content/IRIS.csv")

file

file.info()

input = file[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
output = file["species"]

model= KNeighborsClassifier()

model.fit(input,output)

print(model.predict([[5.1, 3.5, 1.4, 0.2]]))

print(model.predict([[3.9,6.7,3.5,2.6]]))

print(model.predict([[5.9,3.0,5.1,1.8]]))