# -*- coding: utf-8 -*-
"""LinearRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFqRtb4-thgmR4kEkoKV6YlU3fsdLMQ4
"""

import pandas as pd

file=pd.read_csv("/content/simplelinearregression.csv")

file

import matplotlib.pyplot as plt

plt.scatter(file["Age"],file["Premium"])

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(file[["Age"]],file[["Premium"]])

model.predict([[19]])

import pandas as pd

file=pd.read_csv("/content/multiple_linear_regression_dataset.csv")

file

import matplotlib.pyplot as plt

plt.scatter(file["age"],file["experience"],file["income"])

model.fit(file[["age","experience"]],file[["income"]])

model.predict([[47,9]])

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

file=pd.read_csv("/content/simplelinearregression.csv")

x=file[["Age"]]
y=file["Premium"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

model=LinearRegression()

model.fit(x_train,y_train)

model.predict([[25]])

model.predict(x_test)

y_pred=model.predict(x_test)

y_pred

from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,y_pred)

