# -*- coding: utf-8 -*-
"""LogisticRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0Z7BKRC4JXy7VmeG0q4FG9Fu_HmmK_q
"""

import pandas as pd

file=pd.read_csv("/content/breast-cancer.csv").drop("id",axis=1)

file

file.info()

input=file[["radius_mean","texture_mean","perimeter_mean"]]
output=file["diagnosis"]

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

model.fit(input,output)

model.predict([[20.57,17.77,132.9]])

model.predict([[15.57,20.6,165.9]])